### ISSUE TITLE
Internal Error

### ISSUE THREAD

**Issue by erinedyosa** [Itzdvbravo/Tags#1]
Ahm i Need help i haven't config anything and I just want to try the plugin first but i got internal error when i did /tags or /tag i forgot the exact command but yeah it gives me internal error
Thank you

**Comment by Itzdvbravo** [comment]
Ok i'll fix thx

**Comment by Itzdvbravo** [comment]
Can you send me the error for quick fix?

**Comment by Itzdvbravo** [comment]
FIXED
